==== 考试形式和试卷结构

===== 试卷满分及考试时间

考试形式为笔试。考试时间为180分钟。满分为100分。

===== 答题方式

答题方式为闭卷、笔试。

试卷包括试题册和1张答题卡。考生应将英语知识运用和阅读理解部分的答案按要求涂写在答题卡相应题号的选项上，将英译汉和写作部分的答案书写在答题卡指定位置的边框区域内。

===== 考试内容

试题分四部分，共48题，包括英语知识运用、阅读理解、英译汉和写作。

.英语知识运用

主要考查考生对英语知识的综合运用能力。共20小题，每小题0.5分，共10分。

在一篇约350词的文章中留出20个空白，要求考生从每题给出的4个选项中选出最佳答案，使补全后的文章意思通顺、前后连贯、结构完整。

.阅读理解

主要考查考生获取信息、理解文章、猜测重要生词词义并进行推断等方面的能力。该部分由A、B两节组成，共25小题，每小题2分，共50分。

A节（20小题）

本节为多项选择题。共四篇文章，总长度为1500词左右。要求考生阅读文章并回答每篇文章后面的问题。考生需要在每小题所提供的选项（A、B、C、D）中选出唯一正确或是最合适的答案。

每篇文章设5题，共20题。每小题2分，共40分。

B节（5小题）

本节有两种备选题型。每次考试从这两种题型中选择其中的一种形式，或者两种形式的组合进行考查。

本节文章设5小题，每小题2分，共10分。

备选题型包括：

1）多项对应

本节为一篇长度为450~550词的文章，试题内容分为左右两栏，左侧一栏为5道题目，右侧一栏为7个选项。要求考生在阅读后根据文章内容和左侧一栏中提供的信息从右侧一栏中的7个选项中选出对应的5项相关信息。

2）小标题对应

在一篇长度为450~550词的文章前有7个概括句或小标题。这些文字或标题分别是对文章中某一部分的概括或阐述。要求考生根据文章内容和篇章结构从这7个选项中选出最恰当的5个概括句或小标题填入文章空白处。

.翻译

考查考生理解所给英语语言材料并将其译成汉语的能力。要求译文准确、完整、通顺。

要求考生阅读、理解长度为150词左右的一个或几个英语段落，并将其全部译成汉语。共15分。

.写作

该部分由A、B两节组成，主要考查考生的书面表达能力。共2题，25分。

A节

考生根据所给情景写出约100词（标点符号不计算在内）的应用性短文，包括私人和公务信函、备忘录、报告等。共10分。

B节

要求考生根据所规定的情景或给出的提纲，写出一篇150词左右的英语说明文或议论文。提供情景的形式为图画、图表或文字。共15分。

===== 试卷结构

.试卷结构
|===
|部分                 |节 |为考生提供的信息   |指导语语言 |测试要点 |题型 |题目数量 |计分
|I.英语知识运用(10分) |   |1篇文章(约350词)   |英语       |英语知识综合运用能力 |完形填空 多项选择(4选1) |20 |10
|II.阅读理解(50分)    |A  |4篇文章(共约1500词)|英语       |理解重要信息，掌握文章大意，猜测生词词义并进行推断等|多项选择(4选1)|20 |40
|                     |B  |1篇文章(450-500词) |英语  |推理、判断、概括能力|选择搭配|5 |10
|III.翻译(15分)       |   |一个或多个段落(约150词)|英语|理解和表达的准确、完整、通顺|英译汉|1|15
|IV.写作              |A  |规定情景           |英语|书面表达、归纳、概括、表述|应用文(约100词)|1|10
|                     |B  |规定情景或提纲     |英语|书面表达 |短文写作(约150词)|1|15
|总计 | | | | | |45+3 |100
|===

===== 语言知识

.1.语法知识

考生应能熟练地运用基本的语法知识，其中包括：

（1）名词、代词的数和格的构成及其用法；

（2）动词时态、语态的构成及其用法；

（3）形容词与副词的比较级和最高级的构成及其用法；

（4）常用连接词的词义及其用法；

（5）非谓语动词（不定式、动名词、分词）的构成及其用法；

（6）虚拟语气的构成及其用法；

（7）各类从句（定语从句、主语从句、表语从句等）及强调句型的结构及其用法；

（8）倒装句、插入语的结构及其用法。

.2.词汇

考生应能较熟练地掌握5500个左右常用英语词汇以及相关常用词组（详见附录相关部分）。考生应能根据具体语境、句子结构或上下文理解一些非常用词的词义。

===== 语言技能

.1.阅读

考生应能读懂不同题材和体裁的文字材料。题材包括经济、管理、社会、文化、科普等，体裁包括说明文、议论文和记叙文等。

根据阅读材料，考生应能：

（1）理解主旨要义；

（2）理解文中的具体信息；

（3）理解语篇的结构和上下文的逻辑关系；

（4）根据上下文推断重要生词或词组的含义；

（5）进行一定的判断和推理；

（6）理解作者的意图、观点或态度。

.2.写作

考生应能根据所给的提纲、情景或要求完成相应的短文写作。短文应中心思想明确、切中题意、结构清晰、条理清楚、用词恰当、无明显语言错误。