==== 马克思主义基本原理概论

===== 马克思主义是关于无产阶级和人类解放的科学

1. 马克思主义的创立和发展  

马克思主义和马克思主义基本原理。马克思主义产生的社会根源、阶级基础和思想渊源。马克思主义的发展。  

2. 马克思主义的鲜明特征和当代价值  

马克思主义具有鲜明的科学性、革命性、实践性、人民性和发展性。观察当代世界变化的认识工具。指引当代中国发展的行动指南。引领人类社会进步的科学真理。新时代仍然要学习和实践马克思主义。  

===== 世界的物质性及发展规律  

1. 世界多样性与物质统一性  

哲学基本问题及其内容。唯物主义和唯心主义，可知论和不可知论，辩证法和形而上学。马克思主义的物质范畴及其理论意义。物质的根本属性和基本存在形式。实践是自然存在与社会存在区分和统一的基础。人与自然的关系。物质与意识的辩证关系。主观能动性和客观规律性的统一。世界的物质统一性原理及其意义。  

2. 事物的联系和发展  

联系的内涵和特点。事物普遍联系原理的方法论意义。联系与运动、变化、发展。发展的实质。事物发展的过程性。联系和发展的基本环节。  

唯物辩证法的实质和核心。矛盾的同一性和斗争性及其在事物发展中的作用。矛盾的普遍性和特殊性及相互关系。  

量变质变规律和否定之否定规律。  

3. 唯物辩证法是认识世界和改造世界的根本方法  

客观辩证法与主观辩证法的统一。唯物辩证法是伟大的认识工具。矛盾分析法是根本的认识方法。辨证思维方法与现代科学思维方法。学习唯物辩证法，不断増强思维能力。习近平新时代中国特色社会主义思想对唯物辩证法的创造性运用和发展。  

===== 实践与认识及其发展规律  

.1.认识与实践  
实践的本质与基本结构。实践在认识活动中的决定作用。唯物主义和唯心主义对认识本质的不同回答。辩证唯物主义和旧唯物主义对认识本质的不同回答。辩证唯物主义认识论的基本特点。从实践到认识。从认识到实践。实践与认识的辩证运动及其规律。  

.2.真理与价值
真理的客观性。真理的绝对性和相对性及其辩证关系。真理与谬误。实践是检验真理的唯一标准。实践标准的确定性与不确定性。价值及其特征。价值评价及其特点。价值观与核心价值观。真理和价值在实践中的辩证统一。 

.3.认识世界和改造世界
认识世界和改造世界及其辩证关系。改造客观世界和改造主观世界及其辩证关系。从必然走向自由。一切从实际出发，实事求是。实现理论创新和实践创新的良性互动。  

===== 人类社会及其发展规律  

.1.社会基本矛盾及其运动规律  

两种根本对立的历史观。社会存在和社会意识及其辩证关系。物质生产方式是社会历史发展的决定力量。社会存在与社会意识辩证关系原理的重要意义。  

生产力的含义和基本要素。科学技术是生产力中的重要因素。生产关系的含义和内容。生产关系一定要适合生产力状况的规律及其资本论和现实意义。  

经济基础和上层建筑的内涵。国家的起源和实质。上层建筑一定要适合经济基础状况的规律及其理论和现实意义。  

社会形态的内涵。社会形态更替的统一性和多样性。社会形态更替的必然性与人们的历史选择性。社会形态更替的前进性与曲折性。  

.2.社会历史发展的动力  

社会基本矛盾的内容。社会基本矛盾在历史发展中的作用。社会主要矛盾在历史发展中的作用。阶级和阶级斗争的产生和本质。  

阶级斗争在阶级社会发展中的作用。阶级分析方法。社会革命的实质和作用。  

改革在社会发展中的作用。  

科学技术在社会发展中的作用。正确把握科学技术的社会作用。  

.3.人民群众在历史发展中的作用  

两种历史观在历史创造者问题上的对立。唯物史观考察历史创造者的原则。人民群众在创造历史过程中的决定作用。群众观点与群众路线。  

杰出人物的历史作用。辩证地理解和评价个人的历史作用。正确评价无产阶级领神。  

===== 资本主义的本质及规律  

.1.商品经济和价值规律  

商品经济产生的历史条件。商品的二因素和生产商品的劳动的二重性。商品价值量的决定。价值形式的发展与货币的产生。货币的本质和职能。价值规律及其作用。以私有制为基础的商品经济的基本矛盾。  

马克思劳动价值论的理论和实践意义。深化对马克思劳动价值论的认识。  

.2.资本主义经济制度的本质  

前资本主义社会形态的演进和更替。资本主义生产关系的产生。资本的原始积累。资本主义生产方式的确立。  

劳动力成为商品的基本条件。劳动力商品的特点与货币转化为资本。  

资本主义所有制的含义和本质。  

资本主义生产过程的两重性。剩余价值的实质。资本的本质。不变资本和可变资本的区分及其意义。剩余价值率。  

绝对剩余价值和相对剩余价值。超额剩余价值。生产自动化条件下剩余价值的源泉。  

资本主义简单再生产和扩大再生产。资本积累的本质、源泉和后果。资本有机构成。相对过剩人口。资本积累的历史趋势。  

资本循环及其职能形式。产业资本运动的基本前提条件。资本周转及其速度。社会再生产的核心问题及实现条件。  

资本主义工资的本质和形式。平均利润的形成和剩余价值的分割。  

马克思剩余价值理论的意义。  

资本主义基本矛盾。资本主义经济危机。  

.3.资本主义政治制度和意识形态  

资本主义国家的职能和本质。资本主义的民主制度及其本质。资本主义政治制度的进步作用和局限性。  

资本主义意识形态的形成及其本质。辩证地分析资本主义意识形态。  

===== 资本主义的发展及其趋势  

.1.垄断资本主义的形成与发展  

资本主义发展的两个阶段。生产集中与资本集中。垄断的形成、本质及垄断组织。垄断与竞争。金融资本与金融寡头。垄断利润和垄断价格。  

国家垄断资本主义的形成、主要形式和作用。金融垄断资本的发展。垄断资本在世界范固的扩展及其后果。垄断资本国际化条件下的垄断组织。垄断资本主义的基本特征和实质。  

经济全球化及其表现。经济全球化的动因和影响。  

.2.正确认识当代资本主义的新变化  

第二次世界大战后资本主义经济政治新变化的表现和特点。第二次世界大战后资本主义新变化的原因和实质。2008年国际金融危机以来资本主义的矛盾与冲突。  

.3.资本主义的历史地位和发展趋势  

资本主义的历史地位。资本主义为社会主义所代替的历史必然性。社会主义代替资本主义是一个长期的历史过程。  

===== 社会主义的发展及其规律  

.1.社会主义五百年的历史进程  

空想社会主义的产生、发展和局限性。科学社会主义的创立。第一国际和巴黎公社。十月革命胜利与第一个社会主义国家的建立。社会主义在苏联一国的实践。社会主义发展到多个国家。社会主义在中国焕发出强大生机活力。  

.2.科学社会主义一般原则  

科学社会主义一般原则及其主要内容。正确把握科学社会主义一般原则。  

.3.在实践中探索现实社会主义的发展规律  

经济文化相对落后国家建设社会主义的长期性。社会主义发展道路多样性的原因。探索适合本国国情的社会主义发展道路。社会主义在实践探索中开拓前进。  

===== 共产主义崇高理想及其最终实现  

.1.展望未来共产主义新社会  

预见未来社会的方法论原则。共产主义社会的基本特征。  

.2.实现共产主义是历史发展的必然趋势实现共产主义是历史发展的必然。实现共产主义是长期的历史过程。  

共产主义远大理想与中国特色社会主义共同理想。