==== 中国近现代史纲要

===== 反对外国侵略的斗争  

.1.资本一帝国主义对中国的侵略及近代中国社会性质的演变  

鸦片战争前的中国与世界。资本一帝国主义对中国的侵略。近代中国社会的半殖民地封半建性质。近代中国的主要矛盾和历史任务。  

.2.抵御外国武装侵略，争取民族独立的斗争  

反抗外来侵略的斗争。粉碎列强瓜分中国的图谋。  

.3.反侵略战争的失败与民族意识的觉醒  

反侵略战争的失败及其原因。民族意识的觉醒。  

===== 对国家出路的早期探索  

.1. 农民群众斗争风暴的起落  

太平天国农民战争。农民斗争的意义和局限。  

.2.洋务运动的兴衰  

洋务事业的兴办。洋务运动的历史作用及其失败。  

.3.维新运动的兴起和夭折  

戊戌维新运动。戊戌维新运动的意义和教训。  

===== 辛亥革命与君主专制制度的终结  

.1.举起近代民族民主革命的旗朝  

辛亥革命爆发的历史条件。资产阶级革命派的活动。三民主义学说和资产阶级共和国方案。关于革命与改良的辩论。  

.2.辛亥革命与建立民国  

武昌起义与封建帝制的覆灭。中华民国的建立。辛亥革命的历史意义。  

.3.辛亥革命的失败  

封建军阀专制统治的形成。辛亥革命失败的原因和教训。  

===== 开天辟地的大事变  

.1.新文化运动和五四运动  

新文化运动与思想解放的潮流。十月革命对中国的影响。五四运动与中国新民主主义革命的开端。  

.2.马克思主义进一步传播与中国共产党诞生  

中国早期马克思主义思想运动。马克思主义与中国工人运动的结合。中国共产党的创建及其意义。  

.3.中国革命的新局面  

制定革命纲领，发动工农运动。国共合作的形成与大革命的兴起。大革命的意义、失败原因和教训。  

===== 中国革命的新道路  

.1.对革命新道路的艰苦探索  

国民党在全国统治的建立。土地革命战争的兴起。农村包围城市、武装夺取政权的道路。  

.2.中国革命在探索中曲折前进  

土地革命战争的发展及其挫折。遵义会议与中国革命的历史性转折。红军长征的胜利。  

===== 中华民族的抗日战争  

.1.日本发动灭亡中国的侵略战争  

日本灭亡中国的计划及其实施。残暴的殖民统治和中华民族的深重灾难。  

.2.中国人民奋起抗击日本侵略者  

中国共产党举起武装抗日的旗帜。抗日数亡运动和共产党人与部分国民党人合作抗日。西安事变。抗日民族统一战线的形成。全民族抗战开始。  

.3.国民党与抗日的正面战场  

战略防御阶段和战略相持阶段的正面战场。  

.4.中国共产党成为抗日战争的中流砥柱  

全面抗战的路线和持久战的方针。敌后战场的开降与游击战争的发展及其战略地位。坚持抗战、团结、进步的方针。抗日民主根据地的建设。大后方的抗日民主运动和进步文化工作。马克思主义中国化命题的提出。新民主主义理论的系统阐明。延安整风运动。中共七大。  

.5.抗日战争的胜利及其意义  

抗日战争的胜利。中国人民抗日战争在世界反法西斯战争中的地位。抗日战争胜利的原因和意义。  

===== 为新中国而奋斗  

.1.从争取和平民主到进行自卫战争  

抗战胜利后的国际国内局势。中国共产党争取和平民主的斗争。国民党发动内战和解放区军民的自卫战争。两个中国之命运。  

.2.国民党政府处在全民的包围中  

全国解放战争的胜利发展。土地改革与农民的广泛发动。第二条战线的形成和发展。  

中国共产党与民主党派的团结合作。第三条道路的幻灭。中国共产党领导的多党合作、政治协商格局的形成。  

南京国民党政权的覆灭。人民政协与《共同纲领》。中国革命胜利的原因和基本经验。  

===== 社会主义基本制度在中国的确立  

.1.从新民主主义向社会主义过渡的开始  

中华人民共和国的成立及其伟大意义。完成民主革命遗留任务和恢复国民经济。抗美援朝战争。开始向社会主义过渡。  

.2.选择社会主义道路  

工业化的任务和发展道路。过渡时期总路线的提出。实行社会主义改造的必要性和条件。  

.3.有中国特点的向社会主义过渡的道路  

社会主义工业化与社会主义改造同时并举。农业、手工业合作化运动的发展。对资本主义工商业赎买政策的实施。社会主义基本制度在中国的全面确立及其意义。中国进入社会主义初级阶段。  

===== 社会主义建设在探索中曲折发展  

.1.良好的开局  

全面建设社会主义的开端。中共八大路线的制定。《论十大关系》和《关于正确处理人民内部矛盾的问题》的发表。  

.2.探索中的严重曲折  

“大跃进”及其纠正。“文化大革命”及其结束。严重的曲折和深刻的教训。  

.3.建设的成就和探索的成果  

独立的、比较完整的工业体系和国民经济体系的建立。人民生活水平的提高与文化、教育、医疗、科技事业的发展。国际地位的提高与国际环境的改善。探索中形成的建设社会主义的若干重要原则。  

===== 中国特色社会主义的开创与接续发展  

.1.历史性的伟大转折和改革开放的起步  

关于真理标准问题的讨论。中共十一届三中全会的伟大转折。农村改革的突破性进展。拨乱反正任务的胜利完成。  

.2.改革开放和现代化建设新局面的展开  

改革开放的全面展开。中共十三大提出社会主义初级阶段理论和党的基本路线。“三步走”发展战略的制定和实施。  

.3.中国特色社会主义事业的跨世纪发展  

邓小平南方谈话。中共十四大确立社会主义市场经济体制的改革目标。中共十五大高举邓小平理论伟大旗帜，提出跨世纪发展战略。“三个代表”重要思想的提出。  

.4.在新的历史起点上推进中国特色社会主义  

全面建设小康社会战略目标的确定。不断推动经济社会的科学发展。奋力把中国特色社会主义推进到新的发展阶段。改革开放和现代化建设的巨大进展。  

===== 中国特色社会主义进入新时代  

.1.开拓中国特色社会主义更为广周的发展前景  

全面建成小康社会目标的确定。实现民族复兴中国梦的提出。统筹推进“五位一体”总体布局。协调推进”四个全面”战略布局。  

.2.党和国家事业的历史性成就和历史性变革  

开创和发展中国特色社会主义。中共十八大以来五年的成就。中国特色社会主义进入新时代。中国与世界关系的历史性变化。  

.3.夺取新时代中国特色社会主义伟大胜利  

中共十九大的举行。确立习近平新时代中国特色社会主义思想的历史地位。更好发挥宪法在新时代坚持和发展中国特色社会主义中的重大作用。推进国家治理体系和治理能力的现代化。齐心协力走向中华民族伟大复兴的光明前景。新中国发展的两个历史时期及其相互关系。
