==== 思想道德修养与法律基础

.绪论  
1. 我们处在中国特色社会主义新时代  
2. 时代新人要以民族复兴为己任  

做有理想有本领有担当的时代新人。提升思想道德素质与法治素养。  

===== 人生的青春之问  

.1.人生观是对人生的总看法  

人生与人生观。个人与社会的辨证关系。  

.2.正确的人生观  

科学高尚的人生追求。积极进取的人生态度。人生价值的评价与实现。  

.3.创造有意义的人生  

辩证对待人生矛盾。反对错误人生观。成就出彩人生。  

===== 坚定理想信念  

.1.理想信念的内涵及重要性  

理想信念的内涵、特征。理想信念是精神之“钙”。  

.2.崇高的理想信念  

信仰马克思主义。树立共产主义远大理想和中国特色社会主义共同理想。  

.3.在实现中国梦的实践中放飞青春梦想  

正确理解理想与现实的关系。坚持个人理想与社会理想的统为实现中国梦注入青春能量。  

===== 弘扬中国精神  

.1.中国精神是兴国强国之魂  

重精神是中华民族的优秀传统。中国精神是民族精神和时代精神的统一。实现中国梦必须弘扬中国精神。  

.2.爱国主义及其时代要求  

爱国主义的基本内涵。新时代的爱国主义。做忠诚爱国者。  

.3.让改革创新成为青春远航的动力  

创新创造是中华民族最深沉的民族禀赋。改革创新是时代要求。做改革创新生力军。  

===== 践行社会主义核心价值观  

.1.全体人民共同的价值追求  

社会主义核心价值观的基本内容。当代中国发展进步的精神指引。  

.2.坚定价值观自信  

社会主义核心价值观的历史底蕴。社会主义核心价值观的现实基础。社会主义核心价值观的道义力量。  

.3.做社会主义核心价值观的积极践行者  

扣好人生的扣子。勤学修德明辨笃实。  

===== 明大德守公德严私德  

.1.道德及其变化发展  

道德的含义、起源、本质、功能、作用、变化发展。  

.2.吸收借鉴优秀道德成果  

传承中华传统美德。发扬中国革命道德。借鉴人类文明优秀道德成果。  

.3.遵守公民道德准则  

社会主义道德的核心和原则。社会公德。职业道德。家庭美德。个人品德。  

.4.向上向善、知行合一  

向道德模范学习。参与志愿服务活动。引领社会风尚。  

===== 尊法学法守法用法  

.1.社会主义法律的特征和运行  

法律的含义。我国社会主义法律的本质特征。我国社会主义法律的运行。  

.2.以宪法为核心的中国特色社会主义法律体系  

宪法是国家的根本法。我国的实体法律部门。我国的程序法律部门。  

.3.建设中国特色社会主义法治体系  

建设中国特色社会主义法治体系的主要内容。全面依法治国的基本格局。  

.4.坚持走中国特色社会主义法治道路  

坚持中国共产党的领导。坚持人民主体地位。坚持法律面前人人平等。坚持依法治国和以德治国相结合。坚持从中国实际出发。  

.5.培养法治思维  

法治思维及其内涵。尊重和维护法律权威。培养法治思维。  

.6.依法行使权利与履行义务  

法律权利与法律义务。依法行使法律权利。依法履行法律义务。  
